# Generated by Django 5.2.9 on 2026-01-23 15:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biolib', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='campaign_file',
            field=models.FileField(null=True, upload_to='campaigns_inputs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])], verbose_name='Fichier Campagne (CSV)'),
        ),
    ]
