# Generated by Django 5.2.9 on 2026-01-23 15:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biolib', '0002_simulation_campaign_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='enzyme',
            field=models.CharField(choices=[('BsaI', 'BsaI (Golden Gate)'), ('BsmBI', 'BsmBI (Golden Gate)'), ('BbsI', 'BbsI (Golden Gate)'), ('SapI', 'SapI'), ('NotI', 'NotI (BioBrick)')], default='BsaI', max_length=50),
        ),
        migrations.AddField(
            model_name='simulation',
            name='template_file',
            field=models.FileField(null=True, upload_to='simulation_templates/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx', 'xls'])], verbose_name='Fichier Template (Excel)'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='result_file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='biolib.campaigntemplate'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
