# Generated by Django 6.0 on 2026-01-26 21:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biolib', '0003_simulation_enzyme_simulation_template_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigntemplate',
            name='visibility',
            field=models.CharField(choices=[('private', 'Privé (Moi uniquement)'), ('team', 'Visible par mon équipe'), ('public', 'Public (Tout le monde)')], default='private', max_length=20, verbose_name='Visibilité'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='campaign_file',
            field=models.FileField(null=True, upload_to='campaigns_inputs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xls', 'xlsx', 'csv'])], verbose_name='Fichier Campagne (CSV)'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='template_file',
            field=models.FileField(null=True, upload_to='simulation_templates/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv', 'xls', 'xlsx'])], verbose_name='Fichier Template (Excel)'),
        ),
    ]
