# Generated by Django 5.2.9 on 2026-01-30 11:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biolib', '0003_simulation_enzyme_simulation_template_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigntemplate',
            name='visibility',
            field=models.CharField(choices=[('private', 'Privé (Moi uniquement)'), ('team', 'Visible par mon équipe'), ('public', 'Public (Tout le monde)')], default='private', max_length=20, verbose_name='Visibilité'),
        ),
        migrations.AddField(
            model_name='simulation',
            name='custom_enzymes',
            field=models.CharField(blank=True, help_text='Liste des enzymes séparées par des virgules (ex: EcoRI, BamHI)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='simulation',
            name='pcr_primers',
            field=models.TextField(blank=True, help_text='Séquences des amorces (Forward et Reverse) pour simulation PCR', null=True),
        ),
        migrations.AlterField(
            model_name='plasmid',
            name='genbank_file',
            field=models.FileField(blank=True, null=True, upload_to='media/plasmids/', verbose_name='Fichier GenBank'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='campaign_file',
            field=models.FileField(null=True, upload_to='campaigns_inputs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xls', 'xlsx', 'csv'])], verbose_name='Fichier Campagne (CSV)'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='template_file',
            field=models.FileField(null=True, upload_to='simulation_templates/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv', 'xls', 'xlsx'])], verbose_name='Fichier Template (Excel)'),
        ),
    ]
