# Generated by Django 5.2.9 on 2026-01-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biolib', '0004_campaigntemplate_visibility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='name',
            field=models.CharField(default='Ma Simulation', max_length=200, verbose_name='Nom de la simulation'),
        ),
    ]
