# Generated by Django 6.0 on 2026-01-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biolib', '0004_campaigntemplate_visibility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='team',
            name='purpose',
            field=models.CharField(blank=True, choices=[('research', 'Recherche scientifique'), ('campaigns', 'Gestion de campagnes expérimentales'), ('analysis', 'Analyse et exploration de données'), ('teaching', 'Enseignement / travaux pratiques'), ('methods', 'Développement de méthodes / protocoles'), ('collaboration', 'Projet collaboratif inter-équipes'), ('testing', 'Tests / validation technique'), ('archival', 'Archivage et partage de résultats')], max_length=30),
        ),
        migrations.AddField(
            model_name='team',
            name='visibility',
            field=models.CharField(choices=[('private', 'Privée'), ('public', 'Publique')], default='private', max_length=10),
        ),
    ]
