# Generated by Django 6.0 on 2026-01-28 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biolib', '0005_team_description_team_purpose_team_visibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='visibility',
        ),
        migrations.AddField(
            model_name='campaigntemplate',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='biolib.team'),
        ),
        migrations.AddField(
            model_name='correspondence',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='biolib.team'),
        ),
        migrations.AddField(
            model_name='simulation',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='biolib.team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='purpose',
            field=models.CharField(blank=True, choices=[('research', 'Recherche & développement'), ('experiments', 'Expérimentations & campagnes'), ('collaboration', 'Projet collaboratif / enseignement')], max_length=30),
        ),
    ]
