# Generated by Django 5.2.9 on 2026-01-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biolib', '0005_simulation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plasmid',
            name='genbank_file',
            field=models.FileField(blank=True, null=True, upload_to='plasmids/', verbose_name='Fichier GenBank'),
        ),
    ]
