# Generated by Django 6.0.1 on 2026-01-30 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biolib', '0006_alter_plasmid_genbank_file'),
        ('biolib', '0006_remove_team_visibility_campaigntemplate_team_and_more'),
    ]

    operations = [
    ]
