# Generated by Django 5.2.10 on 2026-02-03 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biolib', '0007_merge_20260130_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='visibility',
            field=models.CharField(choices=[('private', 'Privé (Moi uniquement)'), ('team', 'Visible par mon équipe')], default='private', max_length=20, verbose_name='Visibilité'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulations', to='biolib.team', verbose_name='Équipe associée'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
