# Generated by Django 5.2.10 on 2026-02-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biolib', '0008_simulation_visibility_alter_simulation_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='zip_file',
            field=models.FileField(blank=True, null=True, upload_to='simulations/zips/', verbose_name='Archive GenBank (.zip)'),
        ),
    ]
