# Generated by Django 5.2.10 on 2026-02-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biolib', '0009_simulation_zip_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='concentration_file',
            field=models.FileField(blank=True, help_text='Fichier CSV optionnel associant ID de pièce et concentration.', null=True, upload_to='concentrations/', verbose_name='Fichier de concentrations (.csv)'),
        ),
        migrations.AddField(
            model_name='simulation',
            name='default_concentration',
            field=models.FloatField(blank=True, default=200.0, help_text="Utilisée si aucune concentration n'est spécifiée pour une pièce.", null=True, verbose_name='Concentration par défaut (ng/µL)'),
        ),
    ]
