# Generated by Django 5.2.10 on 2026-02-03 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biolib', '0010_simulation_concentration_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='collections',
            field=models.ManyToManyField(blank=True, related_name='simulations', to='biolib.plasmidcollection', verbose_name='Collections utilisées'),
        ),
    ]
