# Generated by Django 6.0.1 on 2026-02-04 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biolib', '0011_simulation_collections'),
    ]

    operations = [
        migrations.AddField(
            model_name='correspondence',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
