# Generated by Django 5.2.9 on 2026-02-04 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biolib', '0011_simulation_collections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plasmid',
            name='collection',
        ),
        migrations.AddField(
            model_name='plasmid',
            name='collections',
            field=models.ManyToManyField(related_name='plasmids', to='biolib.plasmidcollection', verbose_name='Collections'),
        ),
        migrations.AlterField(
            model_name='campaigntemplate',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='biolib.team', verbose_name='Équipe associée'),
        ),
    ]
