# Generated by Django 6.0.1 on 2026-02-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biolib', '0012_correspondence_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='correspondence',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
