# Generated by Django 5.2.9 on 2026-02-05 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biolib', '0012_remove_plasmid_collection_plasmid_collections_and_more'),
        ('biolib', '0013_correspondence_description'),
    ]

    operations = [
    ]
