# Generated by Django 5.2.9 on 2026-02-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biolib', '0015_remove_plasmidcollection_is_public_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correspondence',
            name='is_public',
        ),
        migrations.AddField(
            model_name='correspondence',
            name='admin_feedback',
            field=models.TextField(blank=True, null=True, verbose_name='Raison du refus'),
        ),
        migrations.AddField(
            model_name='correspondence',
            name='publication_status',
            field=models.CharField(choices=[('draft', 'Privé'), ('pending', 'En attente de validation'), ('approved', 'Public (Validé)'), ('rejected', 'Refusé')], default='draft', max_length=20, verbose_name='Statut de publication'),
        ),
    ]
