# Generated by Django 5.2.9 on 2026-02-06 12:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biolib', '0016_remove_correspondence_is_public_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plasmidcollection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date de création'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plasmidcollection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière modification'),
        ),
    ]
