# Generated by Django 5.2.9 on 2026-02-06 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biolib', '0017_plasmidcollection_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plasmidcollection',
            name='publication_status',
            field=models.CharField(blank=True, choices=[('draft', 'Privé'), ('pending', 'En attente de validation'), ('approved', 'Public (Validé)'), ('rejected', 'Refusé')], default='draft', max_length=20, null=True, verbose_name='Statut de publication'),
        ),
    ]
