# Generated by Django 5.2.9 on 2026-02-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biolib', '0018_alter_plasmidcollection_publication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='plasmid',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description / Notes'),
        ),
    ]
