# Generated by Django 6.0.1 on 2026-02-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biolib', '0019_plasmid_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigntemplate',
            name='admin_feedback',
            field=models.TextField(blank=True, null=True, verbose_name='Raison du refus'),
        ),
        migrations.AddField(
            model_name='campaigntemplate',
            name='publication_requested',
            field=models.BooleanField(default=False, verbose_name='Demande de publication envoyée'),
        ),
    ]
