# Generated by Django 5.2.9 on 2026-01-16 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biolib', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plasmidcollection',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='led_teams', to=settings.AUTH_USER_MODEL, verbose_name="Responsable d'équipe"),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administratrice - Accès total'), ('USER', 'Utilisateur - Création et édition de ses propres données'), ('READER', 'Lecteur - Accès en lecture seule')], default='USER', max_length=20),
        ),
    ]
